from __future__ import annotations

from html import escape
from typing import Any


def build_report(case: dict[str, Any], evidence: list[dict[str, Any]], audit_events: list[dict[str, Any]]) -> dict[str, Any]:
    source_types = sorted({str(item.get("type", "UNKNOWN")) for item in evidence})
    return {
        "report_version": "0.1.0",
        "case": case,
        "generated_for": "human investigator review",
        "generated_at": case.get("created_at"),
        "evidence_count": len(evidence),
        "evidence_types": source_types,
        "evidence": evidence,
        "missing_evidence": [],
        "claims": [],
        "uncertainty": [
            "No automated legal liability determination is made by this report.",
            "Synthetic geospatial reconstruction, where shown by the cockpit, is an inference/model and not recorded crash footage.",
            "Evidence conclusions remain subject to investigator review and the completeness and quality of supplied source material.",
        ],
        "audit_event_count": len(audit_events),
        "audit_events": audit_events,
    }


def render_html(report: dict[str, Any]) -> str:
    case = report["case"]
    evidence = report["evidence"]
    uncertainty = report["uncertainty"]
    audit_events = report["audit_events"]

    evidence_rows = "".join(
        "<tr>"
        f"<td>{escape(str(item.get('id', '')))}</td>"
        f"<td>{escape(str(item.get('type', '')))}</td>"
        f"<td>{escape(str(item.get('source', '')))}</td>"
        f"<td>{escape(str(item.get('source_ref') or ''))}</td>"
        f"<td><code>{escape(str(item.get('sha256', '')))}</code></td>"
        f"<td>{escape(str(item.get('ingested_at', '')))}</td>"
        "</tr>"
        for item in evidence
    )
    uncertainty_items = "".join(f"<li>{escape(item)}</li>" for item in uncertainty)

    return f"""<!doctype html>
<html lang=\"en\">
<head>
<meta charset=\"utf-8\">
<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">
<title>ClaimTrace Investigation Report — {escape(str(case.get('id', '')))}</title>
<style>
body{{font-family:Arial,sans-serif;color:#182536;background:#fff;margin:0;padding:32px;line-height:1.45}}
main{{max-width:1100px;margin:0 auto}}
h1{{margin:0 0 6px;font-size:28px}}h2{{margin-top:32px;font-size:18px;border-bottom:1px solid #d8e0e8;padding-bottom:8px}}
.meta{{color:#5f7084;font-size:13px}}.notice{{border-left:4px solid #ff735c;background:#fff5f2;padding:14px;margin:20px 0}}
table{{width:100%;border-collapse:collapse;font-size:12px}}th,td{{padding:9px;border-bottom:1px solid #e1e7ed;text-align:left;vertical-align:top}}th{{background:#f3f6f9}}
code{{word-break:break-all}}li{{margin:7px 0}}.footer{{margin-top:40px;padding-top:16px;border-top:1px solid #d8e0e8;color:#6a7785;font-size:12px}}
</style>
</head>
<body><main>
<header>
<div class=\"meta\">CLAIMTRACE · INVESTIGATION REPORT · VERSION {escape(report['report_version'])}</div>
<h1>{escape(str(case.get('title', 'Untitled investigation')))}</h1>
<div class=\"meta\">Case {escape(str(case.get('id', '')))} · Status {escape(str(case.get('status', '')))}</div>
</header>
<div class=\"notice\"><strong>INVESTIGATOR REVIEW REQUIRED.</strong> This report records evidence and provenance. It does not determine legal liability and must not be treated as a recording of an event when the underlying visualization is synthetic.</div>
<h2>Case context</h2>
<p><strong>Incident time:</strong> {escape(str(case.get('incident_at') or 'Not recorded'))}</p>
<p><strong>Location:</strong> {escape(str(case.get('location') or 'Not recorded'))}</p>
<h2>Evidence register</h2>
<p>{len(evidence)} evidence item(s) registered.</p>
<table><thead><tr><th>ID</th><th>Type</th><th>Source</th><th>Source reference</th><th>SHA-256</th><th>Ingested</th></tr></thead><tbody>{evidence_rows}</tbody></table>
<h2>Uncertainty and limitations</h2><ul>{uncertainty_items}</ul>
<h2>Audit trail</h2>
<p>{len(audit_events)} audit event(s) recorded for this case.</p>
<table><thead><tr><th>Time</th><th>Action</th><th>Actor</th><th>Resource</th></tr></thead><tbody>{''.join(f"<tr><td>{escape(str(item.get('created_at','')))}</td><td>{escape(str(item.get('action','')))}</td><td>{escape(str(item.get('actor_user_id','')))}</td><td>{escape(str(item.get('resource_id','')))}</td></tr>" for item in audit_events)}</tbody></table>
<div class=\"footer\">Generated by ClaimTrace. Source evidence, hashes, custody records and investigator review remain authoritative over this document.</div>
</main></body></html>"""
